# Generated by Django 2.2.3 on 2019-09-30 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20190930_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('note', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('size', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Applicant')),
            ],
        ),
    ]
