# Generated by Django 2.2.3 on 2019-09-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.Applicant'),
        ),
    ]
