# Generated by Django 2.2.3 on 2019-10-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20191001_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Applicant',
        ),
        migrations.AddField(
            model_name='file',
            name='applicant_id',
            field=models.IntegerField(default=0),
        ),
    ]
