# Generated by Django 2.2.3 on 2019-10-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20191003_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
