# Generated by Django 2.2.3 on 2019-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_auto_20191003_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='location_cloud',
            field=models.TextField(default=''),
        ),
    ]
