# Generated by Django 2.2.3 on 2019-10-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20191007_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='File',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.File'),
        ),
    ]
