# Generated by Django 2.2.3 on 2019-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_auto_20191007_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
