# Generated by Django 2.2.3 on 2019-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribe',
            name='raw',
            field=models.TextField(default=''),
        ),
    ]
