# Generated by Django 2.2.3 on 2019-10-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0003_auto_20191007_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribe',
            name='verbatim_text',
            field=models.TextField(default=''),
        ),
    ]
